from __future__ import annotations

import argparse
import copy
import json
from pathlib import Path

from flux_sim.ignition import configure_ignition_from_field_config
from flux_sim.reconstruction import (
    build_sim_provider_model,
    load_ignition_expression_interface,
    load_imported_provider_tree,
)


def main() -> None:
    parser = argparse.ArgumentParser(description="Configure Ignition OPC tags from a Flux Sim FieldAgent config.")
    parser.add_argument("field_config", help="FieldAgent config JSON generated by flux-sim-prepare-online")
    parser.add_argument("--tag-provider", default="default")
    parser.add_argument("--tag-folder", default="FluxSim")
    parser.add_argument("--opc-server", default="Flux Sim")
    parser.add_argument("--endpoint-url", help="Override endpoint URL from FieldAgent config")
    parser.add_argument("--base-url", default="http://localhost:8088/system/webdev/flux")
    parser.add_argument("--token")
    parser.add_argument("--project-location", default="../ignition_flux_project")
    parser.add_argument("--sim-database", default="flux-sim.db", help="Sim import database containing the original Ignition tree")
    parser.add_argument("--provider", help="Imported provider name in --sim-database; defaults to the FieldAgent endpoint name")
    parser.add_argument("--selected-paths-file", type=Path, help="JSON file containing selected_source_paths from the Django sim UI")
    parser.add_argument("--flat", action="store_true", help="Configure generated flat OPC tags instead of preserving the original tree")
    parser.add_argument("--collision-policy", default="o")
    parser.add_argument("--batch-size", type=int, default=1000)
    parser.add_argument("--limit", type=int, help="Configure only the first N generated tags")
    parser.add_argument("--skip-opc-connection", action="store_true")
    parser.add_argument("--skip-wait", action="store_true")
    parser.add_argument("--connect-timeout-seconds", type=float, default=45.0)
    args = parser.parse_args()

    try:
        import fluxy
    except ImportError as exc:
        raise SystemExit("fluxy is required. Run with `uv run --with fluxy-ign ...`.") from exc

    field_config = json.loads(Path(args.field_config).read_text(encoding="utf-8"))
    if not args.flat:
        field_config = with_ignition_tree(
            field_config,
            database_path=Path(args.sim_database),
            provider_name=args.provider,
            selected_paths=load_selected_paths(args.selected_paths_file),
        )
    fx = fluxy.Fluxy(
        base_url=args.base_url,
        token=args.token,
        project_location=args.project_location,
    )
    result = configure_ignition_from_field_config(
        fx,
        field_config,
        tag_provider=args.tag_provider,
        tag_folder=args.tag_folder,
        opc_server=args.opc_server,
        endpoint_url=args.endpoint_url,
        collision_policy=args.collision_policy,
        batch_size=args.batch_size,
        limit=args.limit,
        ensure_connection=not args.skip_opc_connection,
        wait_connected=not args.skip_wait,
        connect_timeout_seconds=args.connect_timeout_seconds,
    )
    print(
        "Configured {count} Ignition OPC tags in {batches} batches under {folder} using OPC server {server}".format(
            count=result.tag_count,
            batches=result.batches,
            folder=result.folder_path,
            server=result.opc_server,
        )
    )


def with_ignition_tree(
    field_config: dict,
    *,
    database_path: Path,
    provider_name: str | None = None,
    selected_paths: list[str] | None = None,
) -> dict:
    if "ignition" in field_config:
        return field_config
    if not database_path.exists():
        return field_config
    selected_provider = provider_name or first_endpoint_name(field_config)
    if not selected_provider:
        return field_config
    tree = load_imported_provider_tree(database_path, selected_provider)
    result = copy.deepcopy(field_config)
    hydrate_source_tag_paths(result, tree)
    result["ignition"] = {"provider_name": selected_provider, "tags": list(tree.tags)}
    if selected_paths is not None:
        result["ignition"]["selected_source_paths"] = selected_paths
    return result


def load_selected_paths(path: Path | None) -> list[str] | None:
    if path is None:
        return None
    payload = json.loads(path.read_text(encoding="utf-8"))
    paths = payload.get("selected_source_paths") if isinstance(payload, dict) else payload
    if not isinstance(paths, list):
        raise SystemExit("selected paths file must be a JSON list or object with selected_source_paths")
    return [str(item) for item in paths]


def hydrate_source_tag_paths(field_config: dict, tree) -> None:
    first_tag = first_field_tag(field_config)
    if first_tag is not None and first_tag.get("source_tag_path"):
        return
    model = build_sim_provider_model(tree, expression_interface=load_ignition_expression_interface())
    path_by_node_id = {
        str(getattr(request, "payload", "") or ""): str(getattr(request, "tag_path", "") or "")
        for request in model.requests
        if getattr(request, "value_source", "") == "opc" and getattr(request, "resolved", True)
    }
    for endpoint in field_config.get("endpoints") or []:
        for device in endpoint.get("devices") or []:
            for tag in device.get("tags") or []:
                node_id = str(tag.get("node_id") or tag.get("opc_item_path") or "")
                source_path = path_by_node_id.get(node_id)
                if source_path:
                    tag["source_tag_path"] = source_path


def first_field_tag(field_config: dict) -> dict | None:
    for endpoint in field_config.get("endpoints") or []:
        for device in endpoint.get("devices") or []:
            for tag in device.get("tags") or []:
                return tag
    return None


def first_endpoint_name(field_config: dict) -> str:
    endpoints = field_config.get("endpoints") or []
    if not endpoints:
        return ""
    return str((endpoints[0] or {}).get("name") or "")


if __name__ == "__main__":
    main()
