# Generated by OpenCode on 2026-05-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LiveScope",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["slug"]},
        ),
        migrations.CreateModel(
            name="LiveCardDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("group", models.CharField(blank=True, max_length=120)),
                ("kind", models.CharField(max_length=120)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="live.livescope",
                    ),
                ),
            ],
            options={
                "ordering": ["scope", "sort_order", "title"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "title"), name="unique_live_card_definition_title"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LiveCardPointDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=255)),
                ("full_path", models.CharField(max_length=1124)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="live.livecarddefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["card", "sort_order", "label"],
                "constraints": [
                    models.UniqueConstraint(fields=("card", "label"), name="unique_live_card_point_label"),
                    models.UniqueConstraint(fields=("card", "full_path"), name="unique_live_card_point_path"),
                ],
            },
        ),
    ]
