# Generated by Django 5.2.14 on 2026-05-14 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('source', models.CharField(choices=[('json_upload', 'JSON upload'), ('ignition_provider', 'Ignition provider')], max_length=40)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('source_sha256', models.CharField(max_length=64)),
                ('root_tag_type', models.CharField(default='Provider', max_length=80)),
                ('total_nodes', models.PositiveIntegerField(default=0)),
                ('folder_count', models.PositiveIntegerField(default=0)),
                ('atomic_tag_count', models.PositiveIntegerField(default=0)),
                ('udt_instance_count', models.PositiveIntegerField(default=0)),
                ('udt_type_count', models.PositiveIntegerField(default=0)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TagNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1200)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('tag_type', models.CharField(max_length=80)),
                ('data_type', models.CharField(blank=True, max_length=80)),
                ('value_source', models.CharField(blank=True, max_length=80)),
                ('type_id', models.CharField(blank=True, max_length=1200)),
                ('opc_server', models.CharField(blank=True, max_length=255)),
                ('opc_item_path', models.CharField(blank=True, max_length=1200)),
                ('source_tag_path', models.CharField(blank=True, max_length=1200)),
                ('expression', models.TextField(blank=True)),
                ('engineering_units', models.CharField(blank=True, max_length=80)),
                ('documentation', models.TextField(blank=True)),
                ('tooltip', models.TextField(blank=True)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('raw_config', models.JSONField(blank=True, default=dict)),
                ('depth', models.PositiveSmallIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('has_children', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base.tagnode')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='base.tagprovider')),
            ],
            options={
                'ordering': ['provider', 'depth', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['provider', 'parent'], name='base_tagnod_provide_575f83_idx'), models.Index(fields=['provider', 'tag_type'], name='base_tagnod_provide_4968b0_idx'), models.Index(fields=['provider', 'value_source'], name='base_tagnod_provide_216a5b_idx'), models.Index(fields=['provider', 'data_type'], name='base_tagnod_provide_970d48_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'path'), name='unique_base_tag_node_path')],
            },
        ),
        migrations.CreateModel(
            name='TagSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1200)),
                ('purpose', models.CharField(choices=[('sim', 'Simulation'), ('runtime', 'Runtime'), ('field', 'Field')], default='sim', max_length=40)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='base.tagprovider')),
            ],
            options={
                'ordering': ['provider', 'purpose', 'path'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'purpose', 'path'), name='unique_base_tag_selection')],
            },
        ),
    ]
