# Generated by Django 5.2.14 on 2026-05-14 16:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def copy_legacy_field_config(apps, schema_editor):
    legacy_endpoint = apps.get_model("field", "FieldEndpoint")
    legacy_device = apps.get_model("field", "FieldDevice")
    legacy_tag = apps.get_model("field", "FieldTag")
    legacy_node = apps.get_model("field", "FieldNode")
    legacy_heartbeat = apps.get_model("field", "FieldAgentHeartbeat")

    base_endpoint = apps.get_model("base", "FieldEndpoint")
    base_device = apps.get_model("base", "FieldDevice")
    base_tag = apps.get_model("base", "FieldTag")
    base_node = apps.get_model("base", "FieldNode")
    base_heartbeat = apps.get_model("base", "FieldAgentHeartbeat")

    for endpoint in legacy_endpoint.objects.all():
        base_endpoint.objects.update_or_create(
            id=endpoint.id,
            defaults={
                "name": endpoint.name,
                "endpoint_url": endpoint.endpoint_url,
                "application_uri": endpoint.application_uri,
                "product_uri": endpoint.product_uri,
                "namespace_uri": endpoint.namespace_uri,
                "enabled": endpoint.enabled,
                "security_policy": endpoint.security_policy,
                "status": endpoint.status,
                "last_seen_at": endpoint.last_seen_at,
                "last_error": endpoint.last_error,
                "created_at": endpoint.created_at,
                "updated_at": endpoint.updated_at,
            },
        )

    for device in legacy_device.objects.all():
        base_device.objects.update_or_create(
            id=device.id,
            defaults={
                "endpoint_id": device.endpoint_id,
                "name": device.name,
                "device_type": device.device_type,
                "browse_path": device.browse_path,
                "enabled": device.enabled,
                "description": device.description,
            },
        )

    for tag in legacy_tag.objects.all():
        base_tag.objects.update_or_create(
            id=tag.id,
            defaults={
                "device_id": tag.device_id,
                "name": tag.name,
                "data_type": tag.data_type,
                "update_rate_ms": tag.update_rate_ms,
                "simulation_type": tag.simulation_type,
                "min_value": tag.min_value,
                "max_value": tag.max_value,
                "variance": tag.variance,
                "initial_value": tag.initial_value,
                "enabled": tag.enabled,
                "description": tag.description,
                "last_value": tag.last_value,
                "last_published_at": tag.last_published_at,
            },
        )

    for node in legacy_node.objects.all():
        base_node.objects.update_or_create(
            id=node.id,
            defaults={
                "endpoint_id": node.endpoint_id,
                "field_tag_id": node.field_tag_id,
                "node_id": node.node_id,
                "browse_name": node.browse_name,
                "display_name": node.display_name,
                "folder_path": node.folder_path,
                "enabled": node.enabled,
                "last_published_value": node.last_published_value,
                "last_published_at": node.last_published_at,
            },
        )

    for heartbeat in legacy_heartbeat.objects.all():
        base_heartbeat.objects.update_or_create(
            id=heartbeat.id,
            defaults={
                "endpoint_id": heartbeat.endpoint_id,
                "instance_id": heartbeat.instance_id,
                "process_id": heartbeat.process_id,
                "version": heartbeat.version,
                "started_at": heartbeat.started_at,
                "last_seen_at": heartbeat.last_seen_at,
                "current_node_count": heartbeat.current_node_count,
                "last_error": heartbeat.last_error,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('field', '0004_seed_default_field_devices'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('endpoint_url', models.CharField(default='opc.tcp://0.0.0.0:4840/flux/field', max_length=255)),
                ('application_uri', models.CharField(default='urn:flux:field', max_length=255)),
                ('product_uri', models.CharField(default='urn:flux:field', max_length=255)),
                ('namespace_uri', models.CharField(default='urn:flux:field:sim', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('security_policy', models.CharField(default='None', max_length=120)),
                ('status', models.CharField(choices=[('disabled', 'Disabled'), ('starting', 'Starting'), ('running', 'Running'), ('error', 'Error')], default='disabled', max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FieldDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('device_type', models.CharField(default='ControlLogix', max_length=120)),
                ('browse_path', models.CharField(default='Devices', max_length=1000)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='base.fieldendpoint')),
            ],
            options={
                'ordering': ['endpoint', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FieldAgentHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=120)),
                ('process_id', models.PositiveIntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=80)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('current_node_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='base.fieldendpoint')),
            ],
            options={
                'ordering': ['endpoint', 'instance_id'],
            },
        ),
        migrations.CreateModel(
            name='FieldTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('bool', 'Boolean'), ('int', 'Integer'), ('float', 'Float'), ('string', 'String')], max_length=20)),
                ('update_rate_ms', models.PositiveIntegerField(default=1000)),
                ('simulation_type', models.CharField(choices=[('toggle', 'Toggle'), ('ramp', 'Ramp'), ('wave', 'Wave'), ('random_walk', 'Random walk'), ('static', 'Static')], default='ramp', max_length=40)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('variance', models.FloatField(default=0.0)),
                ('initial_value', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('last_value', models.JSONField(blank=True, null=True)),
                ('last_published_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='base.fielddevice')),
            ],
            options={
                'ordering': ['device', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FieldNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=255)),
                ('browse_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('folder_path', models.CharField(default='FluxSim', max_length=1000)),
                ('enabled', models.BooleanField(default=True)),
                ('last_published_value', models.JSONField(blank=True, null=True)),
                ('last_published_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='base.fieldendpoint')),
                ('field_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='base.fieldtag')),
            ],
            options={
                'ordering': ['endpoint', 'folder_path', 'browse_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='fielddevice',
            constraint=models.UniqueConstraint(fields=('endpoint', 'name'), name='unique_base_field_device'),
        ),
        migrations.AddConstraint(
            model_name='fieldagentheartbeat',
            constraint=models.UniqueConstraint(fields=('endpoint', 'instance_id'), name='unique_base_field_agent_instance'),
        ),
        migrations.AddConstraint(
            model_name='fieldtag',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='unique_base_field_device_tag'),
        ),
        migrations.AddConstraint(
            model_name='fieldnode',
            constraint=models.UniqueConstraint(fields=('endpoint', 'node_id'), name='unique_base_field_node_id'),
        ),
        migrations.RunPython(copy_legacy_field_config, migrations.RunPython.noop),
    ]
