# Generated by OpenCode on 2026-05-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_fieldagent_config_to_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimDriver",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=80, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("strategy_key", models.CharField(default="generic", max_length=80)),
                ("ignition_driver_names", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True)),
            ],
            options={"ordering": ["key"]},
        ),
        migrations.CreateModel(
            name="SimDevice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("opc_server_name", models.CharField(blank=True, max_length=255)),
                ("endpoint_url", models.CharField(blank=True, max_length=255)),
                ("namespace_uri", models.CharField(blank=True, max_length=255)),
                ("mode", models.CharField(choices=[("standard", "Standard"), ("slow_network", "Slow network")], default="standard", max_length=40)),
                ("response_delay_ms", models.PositiveIntegerField(default=0)),
                ("enabled", models.BooleanField(default=True)),
                ("source_status", models.CharField(blank=True, max_length=255)),
                ("source_detail", models.TextField(blank=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("driver", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="devices", to="base.simdriver")),
                ("provider", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sim_devices", to="base.tagprovider")),
            ],
            options={"ordering": ["provider", "name"]},
        ),
        migrations.CreateModel(
            name="SimDeviceTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_path", models.CharField(max_length=1200)),
                ("tag_name", models.CharField(max_length=255)),
                ("data_type", models.CharField(blank=True, max_length=80)),
                ("value_source", models.CharField(blank=True, max_length=80)),
                ("opc_server", models.CharField(blank=True, max_length=255)),
                ("opc_item_path", models.CharField(blank=True, max_length=1200)),
                ("address_strategy", models.CharField(default="generic", max_length=80)),
                ("address", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=True)),
                ("device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tags", to="base.simdevice")),
                ("provider", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sim_device_tags", to="base.tagprovider")),
                ("tag_node", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sim_device_tags", to="base.tagnode")),
            ],
            options={"ordering": ["provider", "device", "source_path"]},
        ),
        migrations.AddConstraint(
            model_name="simdevice",
            constraint=models.UniqueConstraint(fields=("provider", "name"), name="unique_base_sim_device"),
        ),
        migrations.AddIndex(
            model_name="simdevice",
            index=models.Index(fields=["provider", "driver"], name="base_simdev_provide_a287f0_idx"),
        ),
        migrations.AddConstraint(
            model_name="simdevicetag",
            constraint=models.UniqueConstraint(fields=("provider", "source_path"), name="unique_base_sim_device_tag_source"),
        ),
        migrations.AddIndex(
            model_name="simdevicetag",
            index=models.Index(fields=["provider", "device"], name="base_simdev_provide_1b85d2_idx"),
        ),
        migrations.AddIndex(
            model_name="simdevicetag",
            index=models.Index(fields=["provider", "address_strategy"], name="base_simdev_provide_e0f0d0_idx"),
        ),
    ]
