# Generated by OpenCode on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_sim_device_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="fielddevice",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
