# Generated by OpenCode on 2026-05-19

import django.db.models.deletion
from django.db import migrations, models


def seed_default_sim_server(apps, schema_editor):
    SimServer = apps.get_model("base", "SimServer")
    SimServer.objects.get_or_create(
        name="Flux sim OPC-UA Server",
        defaults={
            "endpoint_url": "opc.tcp://0.0.0.0:4840/flux/sim",
            "application_uri": "urn:flux:sim",
            "product_uri": "urn:flux:sim",
            "namespace_uri": "urn:flux:sim",
            "enabled": True,
            "security_policy": "None",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_tag_behavior_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimServer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("endpoint_url", models.CharField(default="opc.tcp://0.0.0.0:4840/flux/sim", max_length=255)),
                ("application_uri", models.CharField(default="urn:flux:sim", max_length=255)),
                ("product_uri", models.CharField(default="urn:flux:sim", max_length=255)),
                ("namespace_uri", models.CharField(default="urn:flux:sim", max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                ("security_policy", models.CharField(default="None", max_length=120)),
                ("description", models.TextField(blank=True)),
                ("config", models.JSONField(blank=True, default=dict)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="tagprovider",
            name="sim_server",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="tag_providers", to="base.simserver"),
        ),
        migrations.RunPython(seed_default_sim_server, migrations.RunPython.noop),
    ]
