# Generated by Django 5.2.14 on 2026-05-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_kernel_device_tag'),
        ('sim', '0012_sync_materialized_tag_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldtag',
            name='device',
        ),
        migrations.RemoveField(
            model_name='simdevice',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='simdevice',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='simdevicetag',
            name='device',
        ),
        migrations.RemoveField(
            model_name='simdevicetag',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='simdevicetag',
            name='tag_node',
        ),
        migrations.DeleteModel(
            name='FieldDevice',
        ),
        migrations.DeleteModel(
            name='FieldTag',
        ),
        migrations.DeleteModel(
            name='SimDevice',
        ),
        migrations.DeleteModel(
            name='SimDeviceTag',
        ),
    ]
