# Generated by Django 5.2.14 on 2026-05-10 22:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=120)),
                ('path', models.CharField(max_length=1000)),
                ('display_name', models.CharField(max_length=255)),
                ('asset_name', models.CharField(blank=True, max_length=255)),
                ('engineering_units', models.CharField(blank=True, max_length=40)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['asset_name', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='TagSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('interval_seconds', models.PositiveIntegerField(default=30)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['interval_seconds', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LatestTagValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True)),
                ('quality_code', models.CharField(default='Good', max_length=120)),
                ('value_timestamp', models.DateTimeField()),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latest_value', to='runtime.runtimetag')),
            ],
            options={
                'ordering': ['tag__asset_name', 'tag__display_name'],
            },
        ),
        migrations.AddField(
            model_name='runtimetag',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='runtime.tagschedule'),
        ),
        migrations.CreateModel(
            name='TagSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True)),
                ('quality_code', models.CharField(default='Good', max_length=120)),
                ('value_timestamp', models.DateTimeField()),
                ('read_at', models.DateTimeField(db_index=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='runtime.runtimetag')),
            ],
            options={
                'ordering': ['-read_at'],
                'indexes': [models.Index(fields=['tag', '-read_at'], name='runtime_tag_tag_id_308962_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='runtimetag',
            constraint=models.UniqueConstraint(fields=('provider', 'path'), name='unique_runtime_tag_path'),
        ),
    ]
