# Generated by Django 5.2.14 on 2026-05-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runtime', '0003_scheduler_config_balancer'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailytagextreme',
            new_name='runtime_dai_tag_id_bd3777_idx',
            old_name='runtime_dai_tag_id_2b57d3_idx',
        ),
    ]
