# Generated by OpenCode on 2026-05-19

from django.db import migrations, models


def classify_runtime_tags(apps, schema_editor):
    RuntimeTag = apps.get_model("runtime", "RuntimeTag")
    RuntimeTag.objects.filter(path__startswith="FluxLiveDemo/").update(category="simulation")
    RuntimeTag.objects.filter(path__startswith="FluxTraceNavWells/").update(category="trace_stress")
    RuntimeTag.objects.filter(path__startswith="FluxTraceOilfieldLive").update(category="trace_stress")


class Migration(migrations.Migration):

    dependencies = [
        ("runtime", "0004_rename_runtime_dai_tag_id_2b57d3_idx_runtime_dai_tag_id_bd3777_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="runtimetag",
            name="category",
            field=models.CharField(
                choices=[
                    ("production", "Production runtime"),
                    ("simulation", "Simulation"),
                    ("trace_stress", "Trace stress"),
                ],
                default="production",
                max_length=40,
            ),
        ),
        migrations.RunPython(classify_runtime_tags, migrations.RunPython.noop),
    ]
