# Generated by Django 5.2.14 on 2026-05-23 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CellBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('source_sha256', models.CharField(blank=True, max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='DraftCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(blank=True, max_length=120)),
                ('kind', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='cell.cellbundle')),
            ],
            options={
                'ordering': ['bundle__key', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DraftCellPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120)),
                ('label', models.CharField(max_length=255)),
                ('full_path', models.CharField(max_length=1124)),
                ('role', models.CharField(blank=True, max_length=80)),
                ('engineering_units', models.CharField(blank=True, max_length=80)),
                ('include_live', models.BooleanField(default=True)),
                ('include_trace', models.BooleanField(default=False)),
                ('live_order', models.PositiveIntegerField(default=0)),
                ('trace_order', models.PositiveIntegerField(default=0)),
                ('axis_key', models.SlugField(blank=True, max_length=80)),
                ('range_min', models.FloatField(blank=True, null=True)),
                ('range_max', models.FloatField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='cell.draftcell')),
            ],
            options={
                'ordering': ['cell', 'live_order', 'trace_order', 'label'],
            },
        ),
        migrations.AddConstraint(
            model_name='draftcell',
            constraint=models.UniqueConstraint(fields=('bundle', 'slug'), name='unique_draft_cell_slug_per_bundle'),
        ),
        migrations.AddIndex(
            model_name='draftcellpoint',
            index=models.Index(fields=['include_live', 'enabled'], name='cell_point_live_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='draftcellpoint',
            index=models.Index(fields=['include_trace', 'enabled'], name='cell_point_trace_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='draftcellpoint',
            index=models.Index(fields=['full_path'], name='cell_point_full_path_idx'),
        ),
        migrations.AddConstraint(
            model_name='draftcellpoint',
            constraint=models.UniqueConstraint(fields=('cell', 'key'), name='unique_draft_cell_point_key'),
        ),
        migrations.AddConstraint(
            model_name='draftcellpoint',
            constraint=models.UniqueConstraint(fields=('cell', 'full_path'), name='unique_draft_cell_point_path'),
        ),
    ]
