# Generated by Django 5.2.14 on 2026-05-23 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cell', '0001_initial'),
        ('mine', '0002_hmicomponentactionfact_hmicomponentparameterfact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftCellSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=80)),
                ('screen_name', models.CharField(blank=True, max_length=255)),
                ('component_path', models.CharField(blank=True, max_length=1200)),
                ('component_name', models.CharField(blank=True, max_length=255)),
                ('component_type', models.CharField(blank=True, max_length=120)),
                ('bounds', models.JSONField(blank=True, default=dict)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='cell.draftcell')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_sources', to='mine.hmicomponentfact')),
                ('mine_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_sources', to='mine.minerun')),
                ('screen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_sources', to='mine.hmiscreenfact')),
            ],
            options={
                'ordering': ['cell', 'source_type', 'component_name'],
                'indexes': [models.Index(fields=['cell', 'source_type'], name='cell_source_type_idx'), models.Index(fields=['mine_run', 'component_path'], name='cell_source_component_idx')],
            },
        ),
    ]
