# Generated by Django 5.2.14 on 2026-05-23 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cell', '0002_draftcellsource'),
        ('mine', '0002_hmicomponentactionfact_hmicomponentparameterfact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftCellRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=80)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='cell.draftcell')),
                ('to_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='cell.draftcell')),
            ],
            options={
                'ordering': ['from_cell', 'relationship_type', 'sort_order', 'to_cell'],
                'indexes': [models.Index(fields=['relationship_type', 'enabled'], name='cell_rel_type_enabled_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_cell', 'relationship_type', 'to_cell'), name='unique_draft_cell_relationship')],
            },
        ),
        migrations.CreateModel(
            name='DraftCellVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_type', models.CharField(max_length=80)),
                ('source_system', models.CharField(blank=True, max_length=80)),
                ('source_screen_key', models.CharField(blank=True, max_length=1200)),
                ('source_item_key', models.CharField(blank=True, max_length=1200)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visuals', to='cell.draftcell')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_visuals', to='mine.hmicomponentfact')),
                ('mine_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_visuals', to='mine.minerun')),
                ('screen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_visuals', to='mine.hmiscreenfact')),
            ],
            options={
                'ordering': ['cell', 'sort_order', 'visual_type'],
                'indexes': [models.Index(fields=['cell', 'visual_type'], name='cell_visual_type_idx'), models.Index(fields=['mine_run', 'source_item_key'], name='cell_visual_source_idx')],
            },
        ),
    ]
