# Generated by Django 5.2.14 on 2026-05-23 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cell', '0003_draftcellrelationship_draftcellvisual'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftCellComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cell.draftcell')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['cell', '-created_at'], name='cell_comment_latest_idx')],
            },
        ),
    ]
