# Generated by Django 5.2.14 on 2026-05-12 14:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(max_length=80)),
                ('target_path', models.CharField(max_length=1124)),
                ('claimed_by', models.CharField(max_length=120)),
                ('claimed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['expires_at', 'work_type', 'target_path'],
            },
        ),
        migrations.CreateModel(
            name='RefreshLane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('interval_seconds', models.PositiveIntegerField(default=30)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('max_batch_size', models.PositiveIntegerField(default=100)),
                ('max_runtime_ms', models.PositiveIntegerField(default=5000)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['priority', 'interval_seconds', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BrowseNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=120)),
                ('path', models.CharField(max_length=1000)),
                ('parent_path', models.CharField(blank=True, max_length=1000)),
                ('has_children', models.BooleanField(default=False)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_browsed_at', models.DateTimeField(blank=True, null=True)),
                ('next_due_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('cold_score', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['provider', 'path'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'path'), name='unique_browse_node')],
            },
        ),
        migrations.CreateModel(
            name='OptimizedTagPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=120)),
                ('path', models.CharField(max_length=1000)),
                ('full_path', models.CharField(max_length=1124, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_browsed_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('next_due_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('average_duration_ms', models.PositiveIntegerField(default=0)),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tag_paths', to='opt.refreshlane')),
            ],
            options={
                'ordering': ['next_due_at', 'full_path'],
            },
        ),
    ]
