# Generated by Django 5.2.14 on 2026-05-12 14:47

from django.db import migrations


def seed_refresh_lanes(apps, schema_editor):
    refresh_lane = apps.get_model("opt", "RefreshLane")
    lanes = [
        {
            "name": "hot",
            "interval_seconds": 10,
            "priority": 10,
            "max_batch_size": 100,
            "max_runtime_ms": 3_000,
        },
        {
            "name": "warm",
            "interval_seconds": 30,
            "priority": 30,
            "max_batch_size": 250,
            "max_runtime_ms": 5_000,
        },
        {
            "name": "cool",
            "interval_seconds": 60,
            "priority": 60,
            "max_batch_size": 500,
            "max_runtime_ms": 8_000,
        },
        {
            "name": "lazy",
            "interval_seconds": 300,
            "priority": 500,
            "max_batch_size": 50,
            "max_runtime_ms": 2_000,
        },
    ]
    for lane in lanes:
        refresh_lane.objects.update_or_create(name=lane["name"], defaults=lane)


class Migration(migrations.Migration):

    dependencies = [
        ("opt", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_refresh_lanes, migrations.RunPython.noop),
    ]
