# Generated by Django 5.2.14 on 2026-05-12 15:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimHistoryBackfill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('history_prefix', models.CharField(max_length=1200)),
                ('start_at', models.DateTimeField()),
                ('duration_days', models.PositiveIntegerField(default=365)),
                ('interval_seconds', models.PositiveIntegerField(default=3600)),
                ('chunk_size', models.PositiveIntegerField(default=5000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('interval_seconds', models.PositiveIntegerField(default=5)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['interval_seconds', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SimTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='default', max_length=120)),
                ('folder_path', models.CharField(default='FluxSim', max_length=1000)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('data_type', models.CharField(choices=[('Boolean', 'Boolean'), ('Int4', 'Integer'), ('Float8', 'Float')], max_length=20)),
                ('pattern', models.CharField(choices=[('bool_toggle', 'Boolean toggle'), ('int_ramp', 'Integer ramp'), ('float_wave', 'Float wave')], max_length=40)),
                ('enabled', models.BooleanField(default=True)),
                ('baseline', models.FloatField(default=0.0)),
                ('amplitude', models.FloatField(default=1.0)),
                ('step', models.FloatField(default=1.0)),
                ('period_samples', models.PositiveIntegerField(default=10)),
                ('history_enabled', models.BooleanField(default=True)),
                ('last_value', models.JSONField(blank=True, null=True)),
                ('last_write_at', models.DateTimeField(blank=True, null=True)),
                ('next_write_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sample_index', models.PositiveBigIntegerField(default=0)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='sim.simschedule')),
            ],
            options={
                'ordering': ['provider', 'folder_path', 'name'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'folder_path', 'name'), name='unique_sim_tag_path')],
            },
        ),
    ]
