# Generated by Django 5.2.14 on 2026-05-12 15:07

from django.db import migrations


def seed_default_sim_config(apps, schema_editor):
    sim_schedule = apps.get_model("sim", "SimSchedule")
    sim_tag = apps.get_model("sim", "SimTag")

    schedules = {
        "fast-1s": sim_schedule.objects.update_or_create(
            name="fast-1s",
            defaults={"interval_seconds": 1, "enabled": True, "description": "Fast simulation lane"},
        )[0],
        "normal-5s": sim_schedule.objects.update_or_create(
            name="normal-5s",
            defaults={"interval_seconds": 5, "enabled": True, "description": "Normal simulation lane"},
        )[0],
        "slow-10s": sim_schedule.objects.update_or_create(
            name="slow-10s",
            defaults={"interval_seconds": 10, "enabled": True, "description": "Slow simulation lane"},
        )[0],
    }

    tags = [
        {
            "name": "BoolTag",
            "display_name": "Boolean Toggle",
            "data_type": "Boolean",
            "pattern": "bool_toggle",
            "schedule": schedules["fast-1s"],
            "period_samples": 2,
        },
        {
            "name": "IntegerTag",
            "display_name": "Integer Ramp",
            "data_type": "Int4",
            "pattern": "int_ramp",
            "schedule": schedules["normal-5s"],
            "baseline": 0.0,
            "step": 1.0,
            "period_samples": 10,
        },
        {
            "name": "FloatTag",
            "display_name": "Float Wave",
            "data_type": "Float8",
            "pattern": "float_wave",
            "schedule": schedules["slow-10s"],
            "baseline": 50.0,
            "amplitude": 10.0,
            "period_samples": 12,
        },
    ]
    for tag in tags:
        sim_tag.objects.update_or_create(
            provider="default",
            folder_path="FluxSim",
            name=tag["name"],
            defaults=tag,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("sim", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_default_sim_config, migrations.RunPython.noop),
    ]
