# Generated by OpenCode on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sim", "0003_simproviderselection"),
    ]

    operations = [
        migrations.AddField(
            model_name="simtag",
            name="behavior",
            field=models.CharField(
                choices=[
                    ("immediate", "Immediate"),
                    ("slow_response", "Slow response"),
                    ("ignores_write", "Ignores tag write"),
                ],
                default="immediate",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="simtag",
            name="response_delay_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="simtag",
            name="pending_value",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="simtag",
            name="pending_apply_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
