# Generated by OpenCode on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sim", "0004_simtag_behavior"),
    ]

    operations = [
        migrations.AddField(
            model_name="simtag",
            name="mode_config",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="simtag",
            name="behavior",
            field=models.CharField(
                choices=[
                    ("immediate", "Immediate"),
                    ("slow_response", "Slow response"),
                    ("ignores_write", "Ignores tag write"),
                    ("write_to_other_tag_response", "Write to other tag response"),
                ],
                default="immediate",
                max_length=40,
            ),
        ),
    ]
