# Generated by Django 5.2.14 on 2026-05-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0012_sync_materialized_tag_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagconfig',
            name='behavior',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('slow_response', 'Slow response'), ('ignores_write', 'Ignores tag write'), ('write_to_other_tag_response', 'Write to other tag response')], default='immediate', max_length=40),
        ),
    ]
