# Generated by Django 5.2.14 on 2026-05-26 02:38

import django.db.models.deletion
from django.db import migrations, models


POTENTIAL_SYSTEMS = (
    {
        "key": "480VAC_3PH",
        "label": "480 VAC 3-phase",
        "nominal_voltage": "480.00",
        "phase_count": 3,
        "polarity_kind": "ac",
        "description": "Three-phase 480 VAC motor power potential system.",
        "labels": (("L1", "Line 1"), ("L2", "Line 2"), ("L3", "Line 3"), ("PE", "Protective earth")),
    },
    {
        "key": "24VDC_CONTROL",
        "label": "24 VDC control",
        "nominal_voltage": "24.00",
        "phase_count": 1,
        "polarity_kind": "dc",
        "description": "24 VDC control potential system.",
        "labels": (("+24V", "+24 VDC"), ("0V", "0 VDC return"), ("PE", "Protective earth")),
    },
)


def seed_initial_potential_systems(apps, schema_editor):
    PotentialSystem = apps.get_model("schematics", "PotentialSystem")
    PotentialLabel = apps.get_model("schematics", "PotentialLabel")

    for system_spec in POTENTIAL_SYSTEMS:
        potential_system, _created = PotentialSystem.objects.update_or_create(
            key=system_spec["key"],
            defaults={
                "label": system_spec["label"],
                "nominal_voltage": system_spec["nominal_voltage"],
                "phase_count": system_spec["phase_count"],
                "polarity_kind": system_spec["polarity_kind"],
                "description": system_spec["description"],
            },
        )
        for sort_order, (key, label) in enumerate(system_spec["labels"]):
            PotentialLabel.objects.update_or_create(
                potential_system=potential_system,
                key=key,
                defaults={"label": label, "sort_order": sort_order},
            )


def remove_initial_potential_systems(apps, schema_editor):
    PotentialSystem = apps.get_model("schematics", "PotentialSystem")
    PotentialSystem.objects.filter(key__in=[system["key"] for system in POTENTIAL_SYSTEMS]).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(sql='CREATE SCHEMA IF NOT EXISTS "schematics";', reverse_sql=migrations.RunSQL.noop),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('circuit_kind', models.CharField(max_length=40)),
                ('allow_multiple_sources', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': '"schematics"."circuit"',
                'ordering': ['system', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PotentialLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': '"schematics"."potential_label"',
                'ordering': ['potential_system', 'sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='PotentialSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('nominal_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('phase_count', models.PositiveSmallIntegerField(default=1)),
                ('polarity_kind', models.CharField(choices=[('ac', 'AC'), ('dc', 'DC'), ('mixed', 'Mixed')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"schematics"."potential_system"',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='CircuitPotential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potentials', to='schematics.circuit')),
                ('potential_label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circuit_potentials', to='schematics.potentiallabel')),
            ],
            options={
                'db_table': '"schematics"."circuit_potential"',
                'ordering': ['circuit', 'sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ComponentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('label', models.CharField(max_length=180)),
                ('component_kind', models.CharField(max_length=80)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"schematics"."component_template"',
                'ordering': ['key'],
                'indexes': [models.Index(fields=['component_kind'], name='sch_tmpl_kind_idx')],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80)),
                ('name', models.CharField(blank=True, max_length=180)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='schematics.componenttemplate')),
            ],
            options={
                'db_table': '"schematics"."component"',
                'ordering': ['system', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='InternalRelationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
                ('relation_type', models.CharField(default='behavioral', max_length=80)),
                ('condition_key', models.CharField(max_length=120)),
                ('effect_key', models.CharField(max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('component_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_templates', to='schematics.componenttemplate')),
            ],
            options={
                'db_table': '"schematics"."internal_relation_template"',
                'ordering': ['component_template', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Net',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
                ('label', models.CharField(blank=True, max_length=180)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nets', to='schematics.circuit')),
                ('circuit_potential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nets', to='schematics.circuitpotential')),
            ],
            options={
                'db_table': '"schematics"."net"',
                'ordering': ['circuit', 'key'],
            },
        ),
        migrations.AddField(
            model_name='potentiallabel',
            name='potential_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='schematics.potentialsystem'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='potential_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circuits', to='schematics.potentialsystem'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='schematics.component')),
            ],
            options={
                'db_table': '"schematics"."role"',
                'ordering': ['component', 'key'],
            },
        ),
        migrations.CreateModel(
            name='InternalRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
                ('relation_type', models.CharField(default='behavioral', max_length=80)),
                ('condition_key', models.CharField(max_length=120)),
                ('effect_key', models.CharField(max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_relations', to='schematics.component')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relations', to='schematics.internalrelationtemplate')),
                ('source_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relations', to='schematics.role')),
                ('target_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_relations', to='schematics.role')),
            ],
            options={
                'db_table': '"schematics"."internal_relation"',
                'ordering': ['component', 'key'],
            },
        ),
        migrations.CreateModel(
            name='CircuitParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='schematics.circuit')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuit_participations', to='schematics.component')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuit_participations', to='schematics.role')),
            ],
            options={
                'db_table': '"schematics"."circuit_participant"',
                'ordering': ['circuit', 'sort_order', 'component__reference'],
            },
        ),
        migrations.CreateModel(
            name='RoleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('circuit_kind', models.CharField(max_length=40)),
                ('role_kind', models.CharField(max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('component_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_templates', to='schematics.componenttemplate')),
                ('potential_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_templates', to='schematics.potentialsystem')),
            ],
            options={
                'db_table': '"schematics"."role_template"',
                'ordering': ['component_template', 'key'],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='schematics.roletemplate'),
        ),
        migrations.AddField(
            model_name='internalrelationtemplate',
            name='source_role_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relation_templates', to='schematics.roletemplate'),
        ),
        migrations.AddField(
            model_name='internalrelationtemplate',
            name='target_role_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_relation_templates', to='schematics.roletemplate'),
        ),
        migrations.CreateModel(
            name='SchematicSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"schematics"."system"',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='component',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='schematics.schematicsystem'),
        ),
        migrations.CreateModel(
            name='CompileRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='running', max_length=20)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('finding_count', models.PositiveIntegerField(default=0)),
                ('binding_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compile_runs', to='schematics.schematicsystem')),
            ],
            options={
                'db_table': '"schematics"."compile_run"',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='circuit',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuits', to='schematics.schematicsystem'),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('source_kind', models.CharField(max_length=80)),
                ('nominal_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('phase_count', models.PositiveSmallIntegerField(default=1)),
                ('polarity_kind', models.CharField(choices=[('ac', 'AC'), ('dc', 'DC'), ('mixed', 'Mixed')], max_length=20)),
                ('design_enabled', models.BooleanField(default=True)),
                ('potential_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='schematics.potentialsystem')),
                ('producer_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produced_sources', to='schematics.component')),
                ('producer_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produced_sources', to='schematics.role')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='schematics.schematicsystem')),
            ],
            options={
                'db_table': '"schematics"."source"',
                'ordering': ['system', 'name'],
            },
        ),
        migrations.AddField(
            model_name='circuit',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circuits', to='schematics.source'),
        ),
        migrations.CreateModel(
            name='SourcePotential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('potential_label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_potentials', to='schematics.potentiallabel')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potentials', to='schematics.source')),
            ],
            options={
                'db_table': '"schematics"."source_potential"',
                'ordering': ['source', 'sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='schematics.component')),
            ],
            options={
                'db_table': '"schematics"."terminal"',
                'ordering': ['component', 'template__sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='RoleTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_key', models.CharField(blank=True, max_length=40)),
                ('usage', models.CharField(default='conductor', max_length=40)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_links', to='schematics.role')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to='schematics.terminal')),
            ],
            options={
                'db_table': '"schematics"."role_terminal"',
                'ordering': ['role', 'sort_order', 'terminal__key'],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_kind', models.CharField(default='conductor', max_length=80)),
                ('condition_key', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='schematics.circuit')),
                ('net', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='schematics.net')),
                ('from_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='schematics.terminal')),
                ('to_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='schematics.terminal')),
            ],
            options={
                'db_table': '"schematics"."connection"',
                'ordering': ['circuit', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TerminalPotentialBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_key', models.CharField(blank=True, max_length=120)),
                ('binding_kind', models.CharField(default='interface', max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_bindings', to='schematics.circuit')),
                ('circuit_potential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminal_bindings', to='schematics.circuitpotential')),
                ('compile_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_bindings', to='schematics.compilerun')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_bindings', to='schematics.role')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_bindings', to='schematics.terminal')),
            ],
            options={
                'db_table': '"schematics"."terminal_potential_binding"',
                'ordering': ['compile_run', 'circuit', 'terminal__component__reference', 'terminal__key'],
            },
        ),
        migrations.CreateModel(
            name='TerminalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('terminal_kind', models.CharField(default='conductor', max_length=80)),
                ('required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('component_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_templates', to='schematics.componenttemplate')),
            ],
            options={
                'db_table': '"schematics"."terminal_template"',
                'ordering': ['component_template', 'sort_order', 'key'],
            },
        ),
        migrations.AddField(
            model_name='terminal',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminals', to='schematics.terminaltemplate'),
        ),
        migrations.CreateModel(
            name='RoleTerminalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_key', models.CharField(blank=True, max_length=40)),
                ('usage', models.CharField(default='conductor', max_length=40)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('role_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_links', to='schematics.roletemplate')),
                ('terminal_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to='schematics.terminaltemplate')),
            ],
            options={
                'db_table': '"schematics"."role_terminal_template"',
                'ordering': ['role_template', 'sort_order', 'terminal_template__key'],
            },
        ),
        migrations.CreateModel(
            name='ValidationFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], max_length=20)),
                ('code', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('object_kind', models.CharField(blank=True, max_length=80)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=600)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('compile_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='schematics.compilerun')),
            ],
            options={
                'db_table': '"schematics"."validation_finding"',
                'ordering': ['compile_run', 'severity', 'code', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='net',
            constraint=models.UniqueConstraint(fields=('circuit', 'key'), name='unique_sch_net'),
        ),
        migrations.AddConstraint(
            model_name='circuitpotential',
            constraint=models.UniqueConstraint(fields=('circuit', 'key'), name='unique_sch_circuit_potential'),
        ),
        migrations.AddConstraint(
            model_name='potentiallabel',
            constraint=models.UniqueConstraint(fields=('potential_system', 'key'), name='unique_sch_potential_label'),
        ),
        migrations.AddConstraint(
            model_name='internalrelation',
            constraint=models.UniqueConstraint(fields=('component', 'key'), name='unique_sch_relation'),
        ),
        migrations.AddConstraint(
            model_name='circuitparticipant',
            constraint=models.UniqueConstraint(fields=('circuit', 'role'), name='unique_sch_circuit_role'),
        ),
        migrations.AddIndex(
            model_name='roletemplate',
            index=models.Index(fields=['circuit_kind'], name='sch_role_tmpl_circuit_idx'),
        ),
        migrations.AddIndex(
            model_name='roletemplate',
            index=models.Index(fields=['role_kind'], name='sch_role_tmpl_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='roletemplate',
            constraint=models.UniqueConstraint(fields=('component_template', 'key'), name='unique_sch_role_template'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('component', 'key'), name='unique_sch_role'),
        ),
        migrations.AddConstraint(
            model_name='internalrelationtemplate',
            constraint=models.UniqueConstraint(fields=('component_template', 'key'), name='unique_sch_relation_template'),
        ),
        migrations.AddConstraint(
            model_name='component',
            constraint=models.UniqueConstraint(fields=('system', 'reference'), name='unique_sch_component_ref'),
        ),
        migrations.AddIndex(
            model_name='compilerun',
            index=models.Index(fields=['system', 'status'], name='sch_compile_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(fields=('system', 'name'), name='unique_sch_source'),
        ),
        migrations.AddIndex(
            model_name='circuit',
            index=models.Index(fields=['circuit_kind'], name='sch_circuit_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='circuit',
            constraint=models.UniqueConstraint(fields=('system', 'name'), name='unique_sch_circuit'),
        ),
        migrations.AddConstraint(
            model_name='sourcepotential',
            constraint=models.UniqueConstraint(fields=('source', 'key'), name='unique_sch_source_potential'),
        ),
        migrations.AddConstraint(
            model_name='roleterminal',
            constraint=models.UniqueConstraint(fields=('role', 'terminal'), name='unique_sch_role_terminal'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['circuit', 'connection_kind'], name='sch_connection_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='terminalpotentialbinding',
            constraint=models.UniqueConstraint(fields=('compile_run', 'terminal', 'role', 'circuit_potential', 'condition_key'), name='unique_sch_terminal_binding'),
        ),
        migrations.AddConstraint(
            model_name='terminaltemplate',
            constraint=models.UniqueConstraint(fields=('component_template', 'key'), name='unique_sch_terminal_template'),
        ),
        migrations.AddConstraint(
            model_name='terminal',
            constraint=models.UniqueConstraint(fields=('component', 'key'), name='unique_sch_terminal'),
        ),
        migrations.AddConstraint(
            model_name='roleterminaltemplate',
            constraint=models.UniqueConstraint(fields=('role_template', 'terminal_template'), name='unique_sch_role_terminal_template'),
        ),
        migrations.AddIndex(
            model_name='validationfinding',
            index=models.Index(fields=['compile_run', 'severity'], name='sch_finding_severity_idx'),
        ),
        migrations.RunPython(seed_initial_potential_systems, remove_initial_potential_systems),
    ]
