# Generated by Django 5.2.14 on 2026-05-26 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schematics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleContinuity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_key', models.CharField(blank=True, max_length=120)),
                ('continuity_kind', models.CharField(default='conductive', max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': '"schematics"."role_continuity"',
                'ordering': ['role', 'sort_order', 'from_terminal__key', 'to_terminal__key'],
            },
        ),
        migrations.CreateModel(
            name='RoleContinuityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_key', models.CharField(blank=True, max_length=120)),
                ('continuity_kind', models.CharField(default='conductive', max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': '"schematics"."role_continuity_template"',
                'ordering': ['role_template', 'sort_order', 'from_terminal_template__key', 'to_terminal_template__key'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='terminalpotentialbinding',
            name='unique_sch_terminal_binding',
        ),
        migrations.AddConstraint(
            model_name='terminalpotentialbinding',
            constraint=models.UniqueConstraint(fields=('compile_run', 'terminal', 'role', 'circuit_potential', 'condition_key', 'binding_kind'), name='unique_sch_terminal_binding'),
        ),
        migrations.AddField(
            model_name='rolecontinuity',
            name='from_terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_continuities', to='schematics.terminal'),
        ),
        migrations.AddField(
            model_name='rolecontinuity',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continuities', to='schematics.role'),
        ),
        migrations.AddField(
            model_name='rolecontinuity',
            name='to_terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_continuities', to='schematics.terminal'),
        ),
        migrations.AddField(
            model_name='rolecontinuitytemplate',
            name='from_terminal_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_continuity_templates', to='schematics.terminaltemplate'),
        ),
        migrations.AddField(
            model_name='rolecontinuitytemplate',
            name='role_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continuity_templates', to='schematics.roletemplate'),
        ),
        migrations.AddField(
            model_name='rolecontinuitytemplate',
            name='to_terminal_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_continuity_templates', to='schematics.terminaltemplate'),
        ),
        migrations.AddField(
            model_name='rolecontinuity',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='continuities', to='schematics.rolecontinuitytemplate'),
        ),
        migrations.AddConstraint(
            model_name='rolecontinuitytemplate',
            constraint=models.UniqueConstraint(fields=('role_template', 'from_terminal_template', 'to_terminal_template', 'condition_key'), name='unique_sch_role_continuity_tmpl'),
        ),
        migrations.AddConstraint(
            model_name='rolecontinuity',
            constraint=models.UniqueConstraint(fields=('role', 'from_terminal', 'to_terminal', 'condition_key'), name='unique_sch_role_continuity'),
        ),
    ]
