# Generated by Django 5.2.14 on 2026-05-26 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schematics', '0002_rolecontinuity_rolecontinuitytemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='schematics.source')),
                ('source_potential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminals', to='schematics.sourcepotential')),
            ],
            options={
                'db_table': '"schematics"."source_terminal"',
                'ordering': ['source', 'sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SourceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_kind', models.CharField(default='source_conductor', max_length=80)),
                ('condition_key', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_connections', to='schematics.circuit')),
                ('net', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_connections', to='schematics.net')),
                ('source_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='schematics.sourceterminal')),
            ],
            options={
                'db_table': '"schematics"."source_connection"',
                'ordering': ['circuit', 'source_terminal__sort_order', 'source_terminal__key'],
            },
        ),
        migrations.AddConstraint(
            model_name='sourceterminal',
            constraint=models.UniqueConstraint(fields=('source', 'key'), name='unique_sch_source_terminal'),
        ),
        migrations.AddIndex(
            model_name='sourceconnection',
            index=models.Index(fields=['circuit', 'connection_kind'], name='sch_source_conn_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourceconnection',
            constraint=models.UniqueConstraint(fields=('circuit', 'net', 'source_terminal'), name='unique_sch_source_connection'),
        ),
    ]
