# Generated by Django 5.2.14 on 2026-05-26 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schematics", "0003_sourceterminal_sourceconnection_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetTerminal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("connection_kind", models.CharField(default="conductor", max_length=80)),
                ("condition_key", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "circuit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="net_terminals",
                        to="schematics.circuit",
                    ),
                ),
                (
                    "net",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terminals",
                        to="schematics.net",
                    ),
                ),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="net_memberships",
                        to="schematics.terminal",
                    ),
                ),
            ],
            options={
                "db_table": '"schematics"."net_terminal"',
                "ordering": ["circuit", "net", "terminal__component__reference", "terminal__key"],
                "indexes": [models.Index(fields=["circuit", "connection_kind"], name="sch_net_terminal_kind_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("circuit", "net", "terminal"), name="unique_sch_net_terminal")
                ],
            },
        ),
    ]
