# Generated by Django 5.2.14 on 2026-05-26 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schematics', '0004_netterminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80)),
                ('name', models.CharField(blank=True, max_length=180)),
                ('drive_kind', models.CharField(choices=[('vfd', 'VFD'), ('servo', 'Servo'), ('dc_drive', 'DC drive'), ('soft_starter', 'Soft starter')], max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drives', to='schematics.component')),
                ('driven_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_by_drives', to='schematics.component')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='schematics.schematicsystem')),
            ],
            options={
                'db_table': '"schematics"."drive"',
                'ordering': ['system', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='FieldInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80)),
                ('name', models.CharField(blank=True, max_length=180)),
                ('instrument_kind', models.CharField(max_length=80)),
                ('process_variable', models.CharField(blank=True, max_length=80)),
                ('signal_kind', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_instruments', to='schematics.component')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_instruments', to='schematics.schematicsystem')),
            ],
            options={
                'db_table': '"schematics"."field_instrument"',
                'ordering': ['system', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='IOPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=180)),
                ('io_kind', models.CharField(max_length=80)),
                ('direction', models.CharField(choices=[('input', 'Input'), ('output', 'Output'), ('bidirectional', 'Bidirectional')], max_length=20)),
                ('signal_kind', models.CharField(blank=True, max_length=80)),
                ('logical_name', models.CharField(blank=True, max_length=180)),
                ('hardware_address', models.CharField(blank=True, max_length=180)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='io_points', to='schematics.component')),
                ('field_instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='io_points', to='schematics.fieldinstrument')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='io_points', to='schematics.schematicsystem')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='io_points', to='schematics.terminal')),
            ],
            options={
                'db_table': '"schematics"."io_point"',
                'ordering': ['system', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='DriveIOPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_key', models.CharField(max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='io_links', to='schematics.drive')),
                ('io_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_links', to='schematics.iopoint')),
            ],
            options={
                'db_table': '"schematics"."drive_io_point"',
                'ordering': ['drive', 'sort_order', 'function_key'],
            },
        ),
        migrations.AddIndex(
            model_name='drive',
            index=models.Index(fields=['drive_kind'], name='sch_drive_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='drive',
            constraint=models.UniqueConstraint(fields=('system', 'reference'), name='unique_sch_drive_ref'),
        ),
        migrations.AddIndex(
            model_name='fieldinstrument',
            index=models.Index(fields=['instrument_kind'], name='sch_field_inst_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldinstrument',
            index=models.Index(fields=['process_variable'], name='sch_field_inst_pv_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldinstrument',
            index=models.Index(fields=['signal_kind'], name='sch_field_inst_signal_idx'),
        ),
        migrations.AddConstraint(
            model_name='fieldinstrument',
            constraint=models.UniqueConstraint(fields=('system', 'reference'), name='unique_sch_field_instrument_ref'),
        ),
        migrations.AddIndex(
            model_name='iopoint',
            index=models.Index(fields=['direction'], name='sch_io_point_dir_idx'),
        ),
        migrations.AddIndex(
            model_name='iopoint',
            index=models.Index(fields=['io_kind'], name='sch_io_point_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='iopoint',
            index=models.Index(fields=['signal_kind'], name='sch_io_point_signal_idx'),
        ),
        migrations.AddConstraint(
            model_name='iopoint',
            constraint=models.UniqueConstraint(fields=('system', 'reference'), name='unique_sch_io_point_ref'),
        ),
        migrations.AddConstraint(
            model_name='driveiopoint',
            constraint=models.UniqueConstraint(fields=('drive', 'io_point', 'function_key'), name='unique_sch_drive_io_point'),
        ),
    ]
