# Generated by Django 5.2.14 on 2026-05-12 14:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServeCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('claimed', 'Claimed'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serve_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ServeHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=120)),
                ('instance_id', models.CharField(max_length=120)),
                ('platform', models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('running', 'Running'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('error', 'Error')], default='starting', max_length=20)),
                ('pid', models.PositiveIntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=80)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('current_job', models.CharField(blank=True, max_length=255)),
                ('last_error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['service_name', 'instance_id'],
                'constraints': [models.UniqueConstraint(fields=('service_name', 'instance_id'), name='unique_serve_heartbeat_instance')],
            },
        ),
    ]
