# Generated by Django 5.2.14 on 2026-05-22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serve", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServeServiceSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("service_key", models.CharField(max_length=180, unique=True)),
                ("display_name", models.CharField(max_length=180)),
                ("category", models.CharField(max_length=80)),
                (
                    "desired_state",
                    models.CharField(
                        choices=[
                            ("required", "Required"),
                            ("expected", "Expected"),
                            ("optional", "Optional"),
                            ("external", "External"),
                            ("disabled", "Disabled"),
                        ],
                        default="expected",
                        max_length=20,
                    ),
                ),
                (
                    "observed_state",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("missing", "Missing"),
                            ("stale", "Stale"),
                            ("error", "Error"),
                            ("unknown", "Unknown"),
                            ("stopped", "Stopped"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("last_checked_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("detail", models.TextField(blank=True)),
                ("last_error", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "service_key"],
            },
        ),
    ]
