# Generated by Flux on 2026-05-24

from django.db import migrations, models


def rewrite_unsupported_platforms(apps, schema_editor):
    heartbeat = apps.get_model("serve", "ServeHeartbeat")
    heartbeat.objects.filter(platform="windows").update(platform="unknown")


class Migration(migrations.Migration):

    dependencies = [
        ("serve", "0002_serveservicesnapshot"),
    ]

    operations = [
        migrations.RunPython(rewrite_unsupported_platforms, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="serveheartbeat",
            name="platform",
            field=models.CharField(
                choices=[("linux", "Linux"), ("unknown", "Unknown")],
                default="unknown",
                max_length=20,
            ),
        ),
    ]
