# Generated by Django 5.2.14 on 2026-05-12 16:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sim', '0002_seed_default_sim_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('endpoint_url', models.CharField(default='opc.tcp://0.0.0.0:4840/flux/field', max_length=255)),
                ('application_uri', models.CharField(default='urn:flux:field', max_length=255)),
                ('product_uri', models.CharField(default='urn:flux:field', max_length=255)),
                ('namespace_uri', models.CharField(default='urn:flux:field:sim', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('security_policy', models.CharField(default='None', max_length=120)),
                ('status', models.CharField(choices=[('disabled', 'Disabled'), ('starting', 'Starting'), ('running', 'Running'), ('error', 'Error')], default='disabled', max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FieldAgentHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=120)),
                ('process_id', models.PositiveIntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=80)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('current_node_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='field.fieldendpoint')),
            ],
            options={
                'ordering': ['endpoint', 'instance_id'],
                'constraints': [models.UniqueConstraint(fields=('endpoint', 'instance_id'), name='unique_field_agent_instance')],
            },
        ),
        migrations.CreateModel(
            name='FieldNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=255)),
                ('browse_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('folder_path', models.CharField(default='FluxSim', max_length=1000)),
                ('enabled', models.BooleanField(default=True)),
                ('last_published_value', models.JSONField(blank=True, null=True)),
                ('last_published_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='field.fieldendpoint')),
                ('sim_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_nodes', to='sim.simtag')),
            ],
            options={
                'ordering': ['endpoint', 'folder_path', 'browse_name'],
                'constraints': [models.UniqueConstraint(fields=('endpoint', 'node_id'), name='unique_field_node_id'), models.UniqueConstraint(fields=('endpoint', 'sim_tag'), name='unique_field_sim_tag')],
            },
        ),
    ]
