# Generated by Django 5.2.14 on 2026-05-12 16:36

from django.db import migrations


def seed_local_field_endpoint(apps, schema_editor):
    field_endpoint = apps.get_model("field", "FieldEndpoint")
    field_node = apps.get_model("field", "FieldNode")
    sim_tag = apps.get_model("sim", "SimTag")

    endpoint, _created = field_endpoint.objects.update_or_create(
        name="local-field",
        defaults={
            "endpoint_url": "opc.tcp://0.0.0.0:4840/flux/field",
            "application_uri": "urn:flux:field",
            "product_uri": "urn:flux:field",
            "namespace_uri": "urn:flux:field:sim",
            "enabled": True,
            "security_policy": "None",
            "status": "disabled",
        },
    )
    for tag in sim_tag.objects.filter(provider="default", folder_path="FluxSim"):
        field_node.objects.update_or_create(
            endpoint=endpoint,
            sim_tag=tag,
            defaults={
                "node_id": "ns=2;s=FluxSim.%s" % tag.name,
                "browse_name": tag.name,
                "display_name": tag.display_name or tag.name,
                "folder_path": "FluxSim",
                "enabled": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("field", "0001_initial"),
        ("sim", "0002_seed_default_sim_config"),
    ]

    operations = [
        migrations.RunPython(seed_local_field_endpoint, migrations.RunPython.noop),
    ]
