# Generated by Django 5.2.14 on 2026-05-12 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0002_seed_local_field_endpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('device_type', models.CharField(default='ControlLogix', max_length=120)),
                ('browse_path', models.CharField(default='Devices', max_length=1000)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['endpoint', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FieldTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('bool', 'Boolean'), ('int', 'Integer'), ('float', 'Float'), ('string', 'String')], max_length=20)),
                ('update_rate_ms', models.PositiveIntegerField(default=1000)),
                ('simulation_type', models.CharField(choices=[('toggle', 'Toggle'), ('ramp', 'Ramp'), ('wave', 'Wave'), ('random_walk', 'Random walk'), ('static', 'Static')], default='ramp', max_length=40)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('variance', models.FloatField(default=0.0)),
                ('initial_value', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('last_value', models.JSONField(blank=True, null=True)),
                ('last_published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['device', 'name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='fieldnode',
            name='unique_field_sim_tag',
        ),
        migrations.RemoveField(
            model_name='fieldnode',
            name='sim_tag',
        ),
        migrations.AddField(
            model_name='fielddevice',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='field.fieldendpoint'),
        ),
        migrations.AddField(
            model_name='fieldtag',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='field.fielddevice'),
        ),
        migrations.AddField(
            model_name='fieldnode',
            name='field_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='field.fieldtag'),
        ),
        migrations.AddConstraint(
            model_name='fielddevice',
            constraint=models.UniqueConstraint(fields=('endpoint', 'name'), name='unique_field_device'),
        ),
        migrations.AddConstraint(
            model_name='fieldtag',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='unique_field_device_tag'),
        ),
    ]
