# Generated by Django 5.2.14 on 2026-05-12 17:03

from django.db import migrations


def seed_default_field_devices(apps, schema_editor):
    field_endpoint = apps.get_model("field", "FieldEndpoint")
    field_device = apps.get_model("field", "FieldDevice")
    field_tag = apps.get_model("field", "FieldTag")
    field_node = apps.get_model("field", "FieldNode")

    endpoint, _created = field_endpoint.objects.update_or_create(
        name="local-field",
        defaults={
            "endpoint_url": "opc.tcp://0.0.0.0:4840/flux/field",
            "application_uri": "urn:flux:field",
            "product_uri": "urn:flux:field",
            "namespace_uri": "urn:flux:field:sim",
            "enabled": True,
            "security_policy": "None",
            "status": "disabled",
        },
    )
    device, _created = field_device.objects.update_or_create(
        endpoint=endpoint,
        name="FluxLogix001",
        defaults={
            "device_type": "ControlLogix",
            "browse_path": "Devices",
            "enabled": True,
            "description": "Default Flux Field simulated ControlLogix device",
        },
    )
    tags = [
        {
            "name": "BoolTag",
            "data_type": "bool",
            "update_rate_ms": 1000,
            "simulation_type": "toggle",
            "min_value": None,
            "max_value": None,
            "variance": 0.0,
            "initial_value": "false",
        },
        {
            "name": "IntegerTag",
            "data_type": "int",
            "update_rate_ms": 5000,
            "simulation_type": "ramp",
            "min_value": 0.0,
            "max_value": 1000.0,
            "variance": 0.0,
            "initial_value": "0",
        },
        {
            "name": "FloatTag",
            "data_type": "float",
            "update_rate_ms": 10000,
            "simulation_type": "wave",
            "min_value": 0.0,
            "max_value": 100.0,
            "variance": 0.1,
            "initial_value": "50.0",
        },
    ]
    for tag_config in tags:
        tag, _created = field_tag.objects.update_or_create(
            device=device,
            name=tag_config["name"],
            defaults={**tag_config, "enabled": True},
        )
        field_node.objects.update_or_create(
            endpoint=endpoint,
            node_id="ns=2;s=%s.%s" % (device.name, tag.name),
            defaults={
                "field_tag": tag,
                "browse_name": tag.name,
                "display_name": tag.name,
                "folder_path": device.name,
                "enabled": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("field", "0003_fielddevice_fieldtag_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_default_field_devices, migrations.RunPython.noop),
    ]
