# Generated by Django 5.2.14 on 2026-05-23 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=240)),
                ('source_type', models.CharField(choices=[('plc_l5x', 'PLC L5X'), ('plc_l5k', 'PLC L5K'), ('factorytalk', 'FactoryTalk')], max_length=40)),
                ('source_path', models.CharField(max_length=1200)),
                ('source_sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='running', max_length=20)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['source_type', 'status'], name='mine_run_source_status_idx'), models.Index(fields=['source_sha256'], name='mine_run_sha_idx')],
            },
        ),
        migrations.CreateModel(
            name='HmiScreenFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('screen_type', models.CharField(default='display', max_length=80)),
                ('source_path', models.CharField(max_length=1200)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('component_count', models.PositiveIntegerField(default=0)),
                ('tag_reference_count', models.PositiveIntegerField(default=0)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hmi_screens', to='mine.minerun')),
            ],
            options={
                'ordering': ['run', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HmiParameterFileFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_path', models.CharField(max_length=1200)),
                ('parameter_count', models.PositiveIntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hmi_parameter_files', to='mine.minerun')),
            ],
            options={
                'ordering': ['run', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HmiParameterFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('value', models.TextField(blank=True)),
                ('parameter_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='mine.hmiparameterfilefact')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hmi_parameters', to='mine.minerun')),
            ],
            options={
                'ordering': ['parameter_file', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HmiComponentFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('component_type', models.CharField(max_length=120)),
                ('bounds', models.JSONField(blank=True, default=dict)),
                ('global_object_reference', models.CharField(blank=True, max_length=1200)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='mine.hmiscreenfact')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hmi_components', to='mine.minerun')),
            ],
            options={
                'ordering': ['screen', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlcControllerFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('processor_type', models.CharField(blank=True, max_length=120)),
                ('major_version', models.IntegerField(blank=True, null=True)),
                ('comm_path', models.CharField(blank=True, max_length=1200)),
                ('data_type_count', models.PositiveIntegerField(default=0)),
                ('global_tag_count', models.PositiveIntegerField(default=0)),
                ('program_count', models.PositiveIntegerField(default=0)),
                ('program_tag_count', models.PositiveIntegerField(default=0)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plc_controllers', to='mine.minerun')),
            ],
            options={
                'ordering': ['run', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlcDataTypeFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_aoi', models.BooleanField(default=False)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_types', to='mine.plccontrollerfact')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plc_data_types', to='mine.minerun')),
            ],
            options={
                'ordering': ['controller', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlcMemberFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type_name', models.CharField(max_length=255)),
                ('array_dimensions', models.JSONField(blank=True, default=list)),
                ('hidden', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('bit_number', models.IntegerField(blank=True, null=True)),
                ('external_access', models.CharField(blank=True, max_length=120)),
                ('usage', models.CharField(blank=True, max_length=80)),
                ('required', models.BooleanField(blank=True, null=True)),
                ('visible', models.BooleanField(blank=True, null=True)),
                ('constant', models.BooleanField(blank=True, null=True)),
                ('radix', models.CharField(blank=True, max_length=80)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='mine.plcdatatypefact')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plc_members', to='mine.minerun')),
            ],
            options={
                'ordering': ['data_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlcTagFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='Global', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('data_type_name', models.CharField(max_length=255)),
                ('tag_type', models.CharField(default='Base', max_length=80)),
                ('array_dimensions', models.JSONField(blank=True, default=list)),
                ('alias_for', models.CharField(blank=True, max_length=1200)),
                ('hidden', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('external_access', models.CharField(blank=True, max_length=120)),
                ('constant', models.BooleanField(blank=True, null=True)),
                ('radix', models.CharField(blank=True, max_length=80)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='mine.plccontrollerfact')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plc_tags', to='mine.minerun')),
            ],
            options={
                'ordering': ['controller', 'scope', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HmiTagReferenceFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=1200)),
                ('shortcut', models.CharField(max_length=120)),
                ('scope', models.CharField(default='Global', max_length=255)),
                ('base_tag', models.CharField(max_length=255)),
                ('member_path', models.CharField(blank=True, max_length=1200)),
                ('raw_tag_path', models.CharField(blank=True, max_length=1200)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_references', to='mine.hmicomponentfact')),
                ('screen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_references', to='mine.hmiscreenfact')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hmi_tag_references', to='mine.minerun')),
            ],
            options={
                'ordering': ['run', 'screen', 'component', 'base_tag'],
                'indexes': [models.Index(fields=['run', 'shortcut', 'base_tag'], name='mine_hmi_ref_tag_idx'), models.Index(fields=['run', 'scope', 'base_tag'], name='mine_hmi_ref_scope_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='hmiscreenfact',
            constraint=models.UniqueConstraint(fields=('run', 'source_path'), name='unique_mine_screen_per_run_path'),
        ),
        migrations.AddConstraint(
            model_name='hmiparameterfilefact',
            constraint=models.UniqueConstraint(fields=('run', 'source_path'), name='unique_mine_param_file_per_run'),
        ),
        migrations.AddConstraint(
            model_name='hmiparameterfact',
            constraint=models.UniqueConstraint(fields=('parameter_file', 'name'), name='unique_mine_parameter_per_file'),
        ),
        migrations.AddIndex(
            model_name='hmicomponentfact',
            index=models.Index(fields=['run', 'component_type'], name='mine_hmi_component_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='plccontrollerfact',
            constraint=models.UniqueConstraint(fields=('run', 'name'), name='unique_mine_controller_per_run'),
        ),
        migrations.AddConstraint(
            model_name='plcdatatypefact',
            constraint=models.UniqueConstraint(fields=('controller', 'name'), name='unique_mine_type_per_controller'),
        ),
        migrations.AddConstraint(
            model_name='plcmemberfact',
            constraint=models.UniqueConstraint(fields=('data_type', 'name'), name='unique_mine_member_per_type'),
        ),
        migrations.AddIndex(
            model_name='plctagfact',
            index=models.Index(fields=['run', 'scope', 'name'], name='mine_tag_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='plctagfact',
            constraint=models.UniqueConstraint(fields=('controller', 'scope', 'name'), name='unique_mine_tag_per_scope'),
        ),
    ]
