# Generated by Django 5.2.14 on 2026-05-23 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HmiComponentActionFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('action_type', models.CharField(blank=True, max_length=120)),
                ('value', models.TextField(blank=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['component', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HmiComponentParameterFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('value', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['component', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HmiComponentStateFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.CharField(blank=True, max_length=120)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('back_color', models.CharField(blank=True, max_length=120)),
                ('border_color', models.CharField(blank=True, max_length=120)),
                ('border_width', models.CharField(blank=True, max_length=80)),
                ('font_size', models.CharField(blank=True, max_length=80)),
                ('font_family', models.CharField(blank=True, max_length=120)),
                ('text_color', models.CharField(blank=True, max_length=120)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['component', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HmiGlobalObjectLinkFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=1200)),
                ('link_file', models.CharField(blank=True, max_length=1200)),
                ('link_object', models.CharField(blank=True, max_length=1200)),
                ('link_base_object', models.CharField(blank=True, max_length=1200)),
                ('link_size', models.CharField(blank=True, max_length=120)),
                ('link_connections', models.TextField(blank=True)),
                ('link_animations', models.TextField(blank=True)),
                ('link_tooltip_text', models.TextField(blank=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['component', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HmiVbaLinkFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['component', 'id'],
            },
        ),
        migrations.AddField(
            model_name='hmicomponentfact',
            name='children_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hmicomponentfact',
            name='component_path',
            field=models.CharField(blank=True, max_length=1200),
        ),
        migrations.AddField(
            model_name='hmicomponentfact',
            name='depth',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hmicomponentfact',
            name='geometry',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hmicomponentfact',
            name='is_global_instance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hmicomponentfact',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hmicomponentfact',
            name='parent_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_components', to='mine.hmicomponentfact'),
        ),
        migrations.AddField(
            model_name='hmicomponentfact',
            name='parent_path',
            field=models.CharField(blank=True, max_length=1200),
        ),
        migrations.AddField(
            model_name='hmicomponentfact',
            name='sibling_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hmitagreferencefact',
            name='raw',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hmitagreferencefact',
            name='source_kind',
            field=models.CharField(default='component', max_length=80),
        ),
        migrations.AddField(
            model_name='hmitagreferencefact',
            name='source_path',
            field=models.CharField(blank=True, max_length=1200),
        ),
        migrations.AddIndex(
            model_name='hmicomponentfact',
            index=models.Index(fields=['run', 'screen', 'parent_path'], name='mine_hmi_parent_path_idx'),
        ),
        migrations.AddIndex(
            model_name='hmitagreferencefact',
            index=models.Index(fields=['run', 'source_kind'], name='mine_hmi_ref_source_idx'),
        ),
        migrations.AddIndex(
            model_name='hmicomponentfact',
            index=models.Index(fields=['screen', 'component_path'], name='mine_hmi_component_path_idx'),
        ),
        migrations.AddField(
            model_name='hmicomponentactionfact',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='mine.hmicomponentfact'),
        ),
        migrations.AddField(
            model_name='hmicomponentactionfact',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hmi_component_actions', to='mine.minerun'),
        ),
        migrations.AddField(
            model_name='hmicomponentactionfact',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_actions', to='mine.hmiscreenfact'),
        ),
        migrations.AddField(
            model_name='hmicomponentparameterfact',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='mine.hmicomponentfact'),
        ),
        migrations.AddField(
            model_name='hmicomponentparameterfact',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hmi_component_parameters', to='mine.minerun'),
        ),
        migrations.AddField(
            model_name='hmicomponentparameterfact',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_parameters', to='mine.hmiscreenfact'),
        ),
        migrations.AddField(
            model_name='hmicomponentstatefact',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='mine.hmicomponentfact'),
        ),
        migrations.AddField(
            model_name='hmicomponentstatefact',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hmi_component_states', to='mine.minerun'),
        ),
        migrations.AddField(
            model_name='hmicomponentstatefact',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_states', to='mine.hmiscreenfact'),
        ),
        migrations.AddField(
            model_name='hmiglobalobjectlinkfact',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_object_links', to='mine.hmicomponentfact'),
        ),
        migrations.AddField(
            model_name='hmiglobalobjectlinkfact',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hmi_global_object_links', to='mine.minerun'),
        ),
        migrations.AddField(
            model_name='hmiglobalobjectlinkfact',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_object_links', to='mine.hmiscreenfact'),
        ),
        migrations.AddField(
            model_name='hmivbalinkfact',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vba_links', to='mine.hmicomponentfact'),
        ),
        migrations.AddField(
            model_name='hmivbalinkfact',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hmi_vba_links', to='mine.minerun'),
        ),
        migrations.AddField(
            model_name='hmivbalinkfact',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vba_links', to='mine.hmiscreenfact'),
        ),
        migrations.AddIndex(
            model_name='hmicomponentactionfact',
            index=models.Index(fields=['run', 'action_type'], name='mine_hmi_action_type_idx'),
        ),
        migrations.AddIndex(
            model_name='hmicomponentparameterfact',
            index=models.Index(fields=['run', 'name'], name='mine_hmi_param_name_idx'),
        ),
        migrations.AddIndex(
            model_name='hmicomponentstatefact',
            index=models.Index(fields=['run', 'state_id'], name='mine_hmi_state_id_idx'),
        ),
        migrations.AddIndex(
            model_name='hmiglobalobjectlinkfact',
            index=models.Index(fields=['run', 'reference'], name='mine_hmi_global_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='hmivbalinkfact',
            index=models.Index(fields=['run', 'name'], name='mine_hmi_vba_name_idx'),
        ),
    ]
