# Generated by OpenCode on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_ensure_ignition_bridge_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="ignitionbridgeconfig",
            name="role",
            field=models.CharField(
                choices=[("production", "Production"), ("simulator", "Simulator")],
                default="simulator",
                max_length=20,
            ),
        ),
    ]
