from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bridge", "0003_move_ignition_bridge_to_bridge_schema"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE SCHEMA IF NOT EXISTS bridge;
                    DO $$
                    BEGIN
                        IF to_regclass('bridge.ignition_environment') IS NULL THEN
                            IF to_regclass('public.dashboard_ignitionenvironment') IS NOT NULL THEN
                                ALTER TABLE public.dashboard_ignitionenvironment SET SCHEMA bridge;
                                ALTER TABLE bridge.dashboard_ignitionenvironment RENAME TO ignition_environment;
                            ELSE
                                CREATE TABLE bridge.ignition_environment (
                                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    name varchar(120) NOT NULL,
                                    environment_type varchar(20) NOT NULL,
                                    gateway_url varchar(200) NOT NULL,
                                    webdev_base_url varchar(200) NOT NULL,
                                    project_location varchar(1000) NOT NULL,
                                    auth_token varchar(255) NOT NULL,
                                    gateway_username varchar(120) NOT NULL,
                                    demo_project_name varchar(120) NOT NULL,
                                    is_active boolean NOT NULL,
                                    created_at timestamp with time zone NOT NULL,
                                    updated_at timestamp with time zone NOT NULL
                                );
                            END IF;
                        END IF;

                        BEGIN
                            ALTER TABLE bridge.ignition_environment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
                        EXCEPTION
                            WHEN duplicate_object THEN NULL;
                            WHEN object_not_in_prerequisite_state THEN NULL;
                        END;
                    END $$;
                    """,
                    reverse_sql="""
                    DO $$
                    BEGIN
                        IF to_regclass('bridge.ignition_environment') IS NOT NULL
                           AND to_regclass('public.dashboard_ignitionenvironment') IS NULL THEN
                            ALTER TABLE bridge.ignition_environment SET SCHEMA public;
                            ALTER TABLE public.ignition_environment RENAME TO dashboard_ignitionenvironment;
                        END IF;
                    END $$;
                    """,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="IgnitionEnvironment",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("name", models.CharField(max_length=120)),
                        ("environment_type", models.CharField(blank=True, default="", max_length=20)),
                        ("gateway_url", models.URLField(blank=True, default="")),
                        ("webdev_base_url", models.URLField(blank=True, default="")),
                        ("project_location", models.CharField(blank=True, default="", max_length=1000)),
                        ("auth_token", models.CharField(blank=True, default="", max_length=255)),
                        ("gateway_username", models.CharField(blank=True, default="", max_length=120)),
                        ("demo_project_name", models.CharField(blank=True, default="", max_length=120)),
                        ("is_active", models.BooleanField(default=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "db_table": '"bridge"."ignition_environment"',
                        "verbose_name": "Ignition environment",
                        "verbose_name_plural": "Ignition environments",
                    },
                ),
            ],
        ),
    ]
